#include <jni.h>
#include <android/log.h>
#include <gst/gst.h>

#define LOG_TAG "gstreamer_android_texture"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

// Exported by libgstreamer_android.so (generated by the GStreamer ndk-build
// machinery). Initializes GStreamer's registry, environment and plugins.
extern "C" void gst_android_init(JNIEnv* env, jobject context);

extern "C" {

// Fallback binding for org.freedesktop.gstreamer.GStreamer#nativeInit().
// Note: libgstreamer_android.so normally registers its own implementation of
// GStreamer.nativeInit via RegisterNatives in JNI_OnLoad, which takes
// precedence over this symbol. It is kept so init still resolves if a
// prebuilt libgstreamer_android.so without that registration is used.
JNIEXPORT void JNICALL
Java_org_freedesktop_gstreamer_GStreamer_nativeInit(JNIEnv* env, jclass /* klass */,
                                                    jobject context) {
  gst_android_init(env, context);
  LOGI("KANAPKA GStreamer initialized (gst_android_init completed)");
}

// Called from MainActivity right after GStreamer.init(this) so a log line is
// always emitted once GStreamer is up, regardless of which nativeInit
// implementation the JVM bound to.
JNIEXPORT void JNICALL
Java_com_example_gstreamer_1demo_MainActivity_nativeLogGStreamerInit(
    JNIEnv* /* env */, jobject /* thiz */) {
  gchar* version = gst_version_string();
  LOGI("KANAPKA GStreamer initialized: %s (gst_is_initialized=%d)", version,
       gst_is_initialized());
  g_free(version);
}

}  // extern "C"
